### ISSUE TITLE
LocationManager Doesn't Properly Initialize in Simulator

### ISSUE THREAD

**Issue by davidbarsky** [GadaboutTeam/GadaboutiOS#1]
After giving access to app access to the device's location, the console reads out:

`2015-02-02 14:46:48.215 GadaboutiOS[85022:3222781] Location Manager Error: Error Domain=kCLErrorDomain Code=0 "The operation couldn’t be completed. (kCLErrorDomain error 0.)"`

This is only on the simulator. Haven't tested on device.

**Comment by phreakazoid21** [comment]
Have you tried it now? The latest version works fine in mine.

—
Alex Bardasu

**Comment by davidbarsky** [comment]
I haven't; I'll check soon enough.

**Comment by davidbarsky** [comment]
I wasn't simulating the location whoops
