### ISSUE TITLE
RLMRealm instance is deallocated during during write transaction during Facebook Auth

### ISSUE THREAD

**Issue by davidbarsky** [GadaboutTeam/GadaboutiOS#10]
The following was printed out to the console during Facebook authentication:

```
 2015-04-05 19:35:10.049 GadaboutiOS[8991:470307] WARNING: An RLMRealm instance was 
 deallocated during a write transaction and all pending changes have been rolled back.
 Make sure to retain a reference to the RLMRealm for the duration of the write transaction.
```

I suspect that this occurs in the method `- (void)persistCurrentUser` in `UserController.m` in the `@try` block.

To get around this, we could make the realm instance in question a property of `UserController.m` (which is... messy), or begin the write transaction later. On matters of memory management, I’m going to defer to those with more more experience. Thoughts, @phreakazoid21?

**Comment by phreakazoid21** [comment]
I'll look into this soon.
