### ISSUE TITLE
Create Relationship between Invitation and Invited Users

### ISSUE THREAD

**Issue by davidbarsky** [GadaboutTeam/GadaboutiOS#11]
Currently, they're no relationship between the two, so it's not possible to get all users who are attending an event.

**Comment by phreakazoid21** [comment]
We have an endpoint for that which returns the invitations for a specific event. It also returns their reply status, so it's easy to persist and display.

**Comment by davidbarsky** [comment]
my concern is that there is no way to see what users are invited to a given event. the invitation class only has `user_id`, which refers to the sender, not all the receipts.

**Comment by phreakazoid21** [comment]
Nope. The property name is a little confusing, but here's what happens: on the server side we have a derived table that represents a many-to-many relationship between Users and Events. The columns of this table are event_id, user_id and reply. So each row (representing an invitation) tells us the event, who was invited, and what their reply was. The reasoning for this is that the event has no owner per se. We will let the user know who invited them through a notification, but other than that, everyone is equal. This way, if the creator backs out, things can go on just like nothing happened.

**Comment by davidbarsky** [comment]
OK, I should’ve figured the situation is something like that.
