### ISSUE TITLE
Facebook Login

### ISSUE THREAD

**Issue by phreakazoid21** [GadaboutTeam/GadaboutiOS#3]
I wired up the new storyboard for the Facebook login flow. However, at least in the simulator, once I enter my credentials in the browser it gives me this error: 
![ios simulator screen shot 03 feb 2015 02 46 37](https://cloud.githubusercontent.com/assets/467383/6016429/cdb97e0a-ab4f-11e4-9244-f6f6cde5d09d.png)

@davidbarsky You were the one that set up the app. The Facebook side setup might be missing some of the prerequisites listed [here](https://developers.facebook.com/docs/facebook-login/ios/v2.2). I don't have access to the app so I can't check, but it would be cool if you made us admins too when you have the chance.

**Comment by davidbarsky** [comment]
I signed in with my account, and I didn't get the error. Did you try logging in since you've been given admin privileges on Facebook?

**Comment by phreakazoid21** [comment]
Forgot to close this. The issue was in the Facebook configuration; Single SignOn wasn't enabled. I changed it and that's why it works now. Glad it was an easy fix and nothing obscure.
